# Generated by Django 3.2.6 on 2021-11-30 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='date',
        ),
    ]
