# Generated by Django 3.2.6 on 2021-11-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_remove_articles_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='articles',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
