# Generated by Django 3.2.9 on 2021-12-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_generic_new_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_View',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
    ]
