# Generated by Django 3.2.9 on 2021-12-01 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_new_view'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New_View',
            new_name='Register',
        ),
    ]
