# Generated by Django 3.2.9 on 2021-12-01 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_auto_20211201_1808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
